### ISSUE TITLE
Error in proxmox 6.2

### ISSUE THREAD

**Issue by plastilincheg** [Corsinvest/cv4pve-diag#2]
I tried using your utility but got the following error

`root@pve:/usr/local/bin# /usr/local/bin/cv4pve-diag --host=127.0.0.1 --username=root@pam --password=mysecretkey`

```
================ EXCEPTION ================ 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Corsinvest.ProxmoxVE.Diagnostic.Api.Application.CheckQemu(ClusterInfo clusterInfo, List`1 result, IEnumerable`1 validResource, Settings settings)
   at Corsinvest.ProxmoxVE.Diagnostic.Api.Application.Analyze(ClusterInfo clusterInfo, Settings settings)
   at Corsinvest.ProxmoxVE.Diagnostic.Program.<>c__DisplayClass0_0.<Main>b__1()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.ShellHelper.ExecuteConsoleApp(CommandLineApplication app, String[] args)

```

**Comment by franklupo** [comment]
Hi,
you can test this version https://drive.corsinvest.it/index.php/s/fMs445Lw9jXMgFL download and unzip.
The zip contain more files using test directory.

Best regards

**Comment by plastilincheg** [comment]
Hello. In archive windows versions of files. I try to start it on Proxmox host. Not binary for linux. How i can use it? I try to executable c4pve-diag, but errors still

================ EXCEPTION ================ 
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Corsinvest.ProxmoxVE.Diagnostic.Api.Application.CheckQemu(ClusterInfo clusterInfo, List`1 result, IEnumerable`1 validResource, Settings settings)
   at Corsinvest.ProxmoxVE.Diagnostic.Api.Application.Analyze(ClusterInfo clusterInfo, Settings settings)
   at Corsinvest.ProxmoxVE.Diagnostic.Program.<>c__DisplayClass0_0.<Main>b__1() in C:\Users\Daniele\source\repos\OpenSource\ProxmoxVE\cv4pve-diag\src\Corsinvest.ProxmoxVE.Diagnostic\Program.cs:line 56
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass9_0.<OnExecute>b__0()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass144_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Corsinvest.ProxmoxVE.Api.Shell.Helpers.ShellHelper.ExecuteConsoleApp(CommandLineApplication app, String[] args)

**Comment by franklupo** [comment]
Hi,
is corrent. The binary is for linux. 
I'm trying to understand the error codes. I know it goes wrong.

Bets regards

**Comment by franklupo** [comment]
HI,
download https://drive.corsinvest.it/index.php/s/9mfr8fPMsPyc9eQ unzip.
`cv4pve-diag` --host=127.0.0.1 --username=root@pam --password=mysecretkey export-collect

this generates a 'data.json' file. Send me the file that I'm trying to verify is the problem.

Best regards

**Comment by plastilincheg** [comment]
Please, your email.

**Comment by franklupo** [comment]
> Please, your email.
franklupog@gmail.com

**Comment by plastilincheg** [comment]
Sended

**Comment by franklupo** [comment]
The vm 203 does not have the os type set. 
I'm correcting the problem but I don't know if it's right not to have it set. 
Have you changed anything?

**Comment by plastilincheg** [comment]
Yes, that was the problem.

**Comment by franklupo** [comment]
It has been fixed in the new version, but why was it not set?

**Comment by plastilincheg** [comment]
I dont know. Perhaps this was due to recovery from a server crash. I slightly disagree with the warnings that the analyzer gives. Can I send my thoughts in the mail? I'm also interested in whether it is possible to export to a file or send a report to email via sendmail?

**Comment by plastilincheg** [comment]
I dont know. Perhaps this was due to recovery from a server crash. I slightly disagree with the warnings that the analyzer gives. Can I send my thoughts in the mail?

**Comment by franklupo** [comment]
Of course. Send me your opinion

Best regards
